# Generated by Django 3.0.5 on 2020-05-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200530_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='contact_note',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
